server:
  port: ${PORT:10000}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: auth_schema
        hbm2ddl.create_namespaces: true
        
  
  application:
   name: authservice
#  mail:
#    host: smtp.resend.com
#    port: 587
#    username: apikey
#    password: ${RESEND_API_KEY}
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL}