server:
  port: ${PORT:10000}

spring:
  application:
    name: tripservice

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: trip_schema
        hbm2ddl.create_namespaces: true

  mail:
    host: smtp-relay.brevo.com
    port: 2525
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}
    properties:
      mail.smtp.auth: true

geoapify:
  key: ${GEOAPIFY_KEY}

openrouteservice:
  key: ${ORS_KEY}

exchange:
  url: ${EXCHANGE_URL}

weather:
  url: ${WEATHER_URL}

openrouter:
  key: ${OPENROUTER_KEY}

cashfree:
  app:
    id: ${CASHFREE_APP_ID}
  secret:
    key: ${CASHFREE_SECRET_KEY}
  base:
    url: ${CASHFREE_BASE_URL}

auth:
  service:
    url: ${AUTH_SERVICE_URL}

internal:
  auth:
    token: ${INTERNAL_SECRET}
  base-url: ${AUTH_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    root: INFO
    